version: "3"

services:
  app:
    build:
      context: .
    container_name: tasklist
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres?currentSchema=tasklist
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=bestuser
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - '8080:8080'
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bestuser
      - POSTGRES_DB=postgres
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d

