
# мы здесь показали, как нужно подключаться к бд
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres?currentSchema=public
    username: postgres
    password: bestuser
    driver-class-name: org.postgresql.Driver
#url:


#     это настройка sql, она будет выполняться всегда
  sql:
    init:
      mode: never # never потому-что теперь у нас liquibase
      continue-on-error: false # если будет ошибка, то будет останавливаться
#      data-locations: classpath:demo_data.sql
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: public


# мы тут описали, локацию описание этого файла
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml


security:
  jwt:
    # тут мы получили секрет на base 64 encoder
    secret: bGtqZGZsO2thc2RqZmxramFza2ZqYWxza29
    access: 360000
    refresh: 2592000000

server:
  port: 8080
  address: localhost

springdoc:
  override-with-generic-response: false # уйдут излишние запросы ошибок в Swagger

























#spring:
#datasource:
#  url: jdbc:mysql://localhost:3306/my_db?useSSL=false
#  username: bestuser
#  password: bestuser
#  driver-class-name: com.mysql.cj.jdbc.Driver