
#postgres?currentSchema=
spring:
#  cache:
#    type: redis
#    cache-names: redis-cache
#  data:
#    redis:
#      host: localhost
#      port: 6379
#      password: cXdlcXdl
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=tasklist
    username: postgres
    password: bestuser
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: never # never потому-что теперь у нас liquibase
      continue-on-error: false # если будет ошибка, то будет останавливаться
  #      data-locations: classpath:demo_data.sql
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: tasklist


# мы тут описали, локацию описание этого файла
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml


security:
  jwt:
    # тут мы получили секрет на base 64 encoder
    secret: bGtqZGZsO2thc2RqZmxramFza2ZqYWxza29
    access: 360000
    refresh: 2592000000

springdoc:
  override-with-generic-response: false # уйдут излишние запросы ошибок в Swagger






